### PR TITLE
Fix build: Start using GitHub Actions + Replace test image URL

### PR DESCRIPTION
**Pull request by StephenChan**
(Edit) PR summary:

- Switch from Travis CI to GitHub Actions; for issue #47.
  - In the process, saw that building scikit-image no longer worked for some reason. So this PR fixes that by updating scikit-image, and in the process has to drop Python 3.5 (it's EOL since 2020 anyway).
- The wisc.edu baboon image URL, used in some unit tests, is no longer available. This PR switches the URL to a Wikimedia image of roughly similar size.

Originally wanted to make this two PRs, but both tasks were required for the build to pass, which is required to merge PRs.

(Original PR text below:)

> For issue #47.

### CODE REVIEW

**Comment by StephenChan** [comment]
scikit-image failed to build: `ModuleNotFoundError: No module named 'numpy'`: https://github.com/beijbom/pyspacer/runs/5561549826

This old Travis build with the same versions of numpy and scikit-image succeeded: https://travis-ci.org/github/beijbom/pyspacer/jobs/725155186

That old build's pip was 19.3, current pip is 22.0.4. I'll see if 19.3 makes it work again, at least to help understand what's happening.

**Comment by StephenChan** [comment]
I told it to use pip 19.3 and it used pip 21.1.1 instead. No idea why, but I guess that route goes out the window.

We're on scikit-image 0.15.0. This issue suggests that scikit-image 0.17.x (but not 0.18.x) may improve the numpy import situation in `setup.py` - so 0.17.x could be worth a shot: https://github.com/scikit-image/scikit-image/issues/1329

**Comment by StephenChan** [comment]
@beijbom I ended up moving PR #45's commit over to this PR, so that it's just a single PR which fixes the build.

**Review by beijbom — APPROVED** [review]

**Comment by StephenChan** [comment]
@beijbom Thanks - could you also remove Travis CI from the "required statuses" for PRs? Should be in the repo settings.

**Comment by StephenChan** [comment]
@beijbom Reminder - could you 1) remove Travis CI from "required statuses" and 2) re-approve the PR? (I didn't realize adding another commit would dismiss your previous review as stale.)

**Review by beijbom — APPROVED** [review]

**Comment by beijbom** [comment]
Fixed. Sorry for the delay.

**Comment by StephenChan** [comment]
Np, thanks!

**Pull request merged**
